### ISSUE TITLE
Add maximum and minimum beside average for cpu and memory

### ISSUE THREAD

**Issue by patanachai** [atlassian/themis#20]
There is a use case where we want a conservative scale down. For example, wait for all resources to not being used at all before start scaling down, i.e. maximum of cpu usage < 0.02

**Comment by whummer** [comment]
Good suggestion, this should be relatively easy to implement. We'll add this feature shortly.

**Comment by whummer** [comment]
Added support for min/max values in 538933105d8ae0f3223444c62d71fdf1e8e3be51 . Documentation for using the expression language will be updated soon
