### ISSUE TITLE
Themis is showing NaN in GUI for all active clusters

### ISSUE THREAD

**Issue by xavierpayne** [atlassian/themis#9]
I added logging and have verified that the calls to Ganglia are returning data. I also verified that the aws-cli commands are working and using the correct SSH key. But all the instances show NaN in the GUI for their CPU and memory data.

I am adding logging to try and debug further.
![screen shot 2016-08-26 at 10 27 30 am](https://cloud.githubusercontent.com/assets/10713122/18014501/0d8bd20a-6b78-11e6-945d-396cf3482d06.png)

**Comment by xavierpayne** [comment]
It seems to be unhappy with something about the "type." From the log:
2016-08-26 21:12:25,892 WARNING: scaling.server: Error getting monitoring info for cluster j-XXXXXXXXXX: 'type'

Is it mandatory my cluster has "TASK" instances?

**Comment by xavierpayne** [comment]
I added a "Task" instance. Now I see this:

![screen shot 2016-08-26 at 10 27 30 am](https://cloud.githubusercontent.com/assets/10713122/18021066/c267ed64-6b99-11e6-9079-866b97132632.png)

It looks like only task instances display their CPU and Memory at present. Is this a bug or by design? :)

The offending code block seems to be:
def add_stats(data):

In:
src/themis/util/monitoring.py

**Comment by whummer** [comment]
@xavierpayne Yep, that looks like a bug. We'll look into it, thanks for reporting!

**Comment by whummer** [comment]
@xavierpayne Can you please confirm that this issue is resolved with the recent change?

**Comment by xavierpayne** [comment]
Confirmed thanks! :)
